version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jsdom
    versions:
    - 16.5.0
    - 16.5.1
    - 16.5.2
